// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp5rEduinGE5GAeKADkWxO6c9XDB4KFbQ',
    appId: '1:344656214240:web:e71b98efb104e794fe3885',
    messagingSenderId: '344656214240',
    projectId: 'chat-app-5e7d2',
    authDomain: 'chat-app-5e7d2.firebaseapp.com',
    storageBucket: 'chat-app-5e7d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG-uiQLL22jUAEoz5fAlQOxnOO7uP-Lcw',
    appId: '1:344656214240:android:d23a6f35fe344733fe3885',
    messagingSenderId: '344656214240',
    projectId: 'chat-app-5e7d2',
    storageBucket: 'chat-app-5e7d2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8a2ybIUEeHpSblK4_CGQQ30VixVNGr6c',
    appId: '1:344656214240:ios:8f49e0e2ee04cbc8fe3885',
    messagingSenderId: '344656214240',
    projectId: 'chat-app-5e7d2',
    storageBucket: 'chat-app-5e7d2.firebasestorage.app',
    iosBundleId: 'com.example.cubitproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp5rEduinGE5GAeKADkWxO6c9XDB4KFbQ',
    appId: '1:344656214240:web:959ff9eecdca4487fe3885',
    messagingSenderId: '344656214240',
    projectId: 'chat-app-5e7d2',
    authDomain: 'chat-app-5e7d2.firebaseapp.com',
    storageBucket: 'chat-app-5e7d2.firebasestorage.app',
  );
}
